%   TITLE     : ROBUST ADAPTIVE COMPENSATION OF FBRTHS TESTING WITH UNCERTAIN COMPLIANCE SPRING AND FORCE MEASUREMENT NOISE
%   SUBJECT   : INPUTS - REFERENCE STRUCTURE
%   AUTHOR    : DIEGO ARAYA IGLESIAS
%% INITIALIZING
clc;clear;close all;format shortG;
% RUN SCRIPTS
TMC01_S02_REFERENCE_STRUCTURE
TMC01_S03_SUBSTRUCTURE
TMC01_S04_TRANSFER_FUNCTIONS
TMC01_S05_SENSORS

